### PR TITLE
Segemented Sieve for Prime number generation.

### PR DESCRIPTION
**Pull request by CaptainDaVinci**
Added _Segemented sieve_ for generating primes in a given range. This method provides more efficiency in terms of memory.

### CODE REVIEW

**Comment by CaptainDaVinci** [comment]
Hello, I am new to open source contribution, could someone be kind enough to explain "All checks have failed". As I understand, Travis CI is used for software testing, but I am not sure where the error is.

**Comment by prateekiiest** [comment]
thanks for the contriibution

**Comment by prateekiiest** [comment]
But once travisCI is not fixed we will not be able to merge this

**Comment by CaptainDaVinci** [comment]
The above code is in python 3.x, should I refactor it to python 2.6+ ?

**Comment by prateekiiest** [comment]
yeah I think you should, because the travis doesnt work for py3 now.

**Comment by prateekiiest** [comment]
@CaptainDaVinci could you update requirements.txt?
issue #60

**Comment by CaptainDaVinci** [comment]
Aren't all the dependencies updated in the requirements.txt after this commit https://github.com/prateekiiest/Code-Sleep-Python/commits/master/requirements.txt ?

**Comment by prateekiiest** [comment]
No, it still does not have the required libraries like mvcrt, requests

**Comment by CaptainDaVinci** [comment]
Ok, I will try adding the remaining libraries. However, some of the code is in python 3, Travis would still fail, wouldn't it?

**Comment by prateekiiest** [comment]
dependancies need to be updated for that in the travis.yml file.
I will do that

**Comment by prateekiiest** [comment]
Ran locally.
Looks good

**Pull request merged**
