### PR TITLE
Removed .DS_Store file and added this to .gitignore

### PR DESCRIPTION
**Pull request by mushmula27**
## ISSUE NUMBER

#170

### CODE REVIEW

**Comment by prateekiiest** [comment]
Is this commit not under another pull request #174 @mushmula27 ?

**Comment by mushmula27** [comment]
Opps, sorry, I branched off ds-store-ignored by mistake for my other PR. I've cleaned up the commits for #174 now.

**Comment by prateekiiest** [comment]
Should this be closed then?

**Comment by mushmula27** [comment]
I removed the conflicts so these are 2 separate PRs. So this should be merged ideally.

**Pull request merged**
