### PR TITLE
Logistic Regression for classification problems

### PR DESCRIPTION
**Pull request by epicalyx**
Added implementation for logistic regression in python.

Thank you for your contribution. Please provide the details requested below.

## ISSUE NUMBER

Please provide a link to the issue this pull request addresses.

## SHORT DESCRIPTION

Please provide a short description of the changes.

## TESTING

Please provide the necessary steps to test the solution.

### CODE REVIEW

**Comment by prateekiiest** [comment]
Any updates ??

**Comment by epicalyx** [comment]
Sorry for not commiting any changes but I haven't used the algorithm that is mentioned in the README file. Shall I make another folder that contains all classification algorithms?

**Comment by prateekiiest** [comment]
Yes please

**Comment by Sanat-Mishra** [comment]
The issues pointed out by CodeClimate are easy to fix. Can I do them? Or is it not possible to assign the same project to two people at once? ( It's marked stale already?!)

**Comment by prateekiiest** [comment]
yes @Sanat-Mishra you can go ahead.
Sorry for the delay.

**Pull request closed without merging**
