### PR TITLE
Fix issue 123 requirements

### PR DESCRIPTION
**Pull request by Cereal84**
#123 

## ISSUE NUMBER 

123
Please provide a link to the issue this pull request addresses.

## SHORT DESCRIPTION

Add some requirements.txt files and updates others.
Meanwhile I've found some problems running py_api, Hangman and Sprint.

### CODE REVIEW

**Comment by prateekiiest** [comment]
could you please squash all the commits into one?

**Comment by Cereal84** [comment]
sure

**Comment by Cereal84** [comment]
I've squashed the commits.. I guess.

**Comment by prateekiiest** [comment]
Thanks @Cereal84 for the PR!!

**Comment by Cereal84** [comment]
You are welcome :).

**Pull request merged**
