### PR TITLE
Added Kmeans algorithm

### PR DESCRIPTION
**Pull request by Xirzag**
## ISSUE NUMBER
Add new clustering python project
https://github.com/prateekiiest/Code-Sleep-Python/issues/164

## SHORT DESCRIPTION

Just added a Kmeans project that shows how this algorithm works with comments. It also created a graph that show how the centroids move in every iteration.

## TESTING

Run the Kmeans.pynb jupyter notebook, it should create plots like kmeans.jpg. The centroids are positioned randomly, so the result may change in every execution

### CODE REVIEW

**Comment by prateekiiest** [comment]
Your commits somehow got all mixed up with the previous ones :D

**Comment by Xirzag** [comment]
Ok, I'll redo the pull request

**Comment by prateekiiest** [comment]
Should I close this then?

**Comment by Xirzag** [comment]
Yes

**Pull request closed without merging**
