### PR TITLE
Superellipse 

### PR DESCRIPTION
**Pull request by Subhajit135**
Thank you for your contribution. Please provide the details requested below.

## ISSUE NUMBER

Please provide a link to the issue this pull request addresses.

## SHORT DESCRIPTION
Implementation of superellipse in python using matplotlib.

## TESTING

Please provide the necessary steps to test the solution.

### CODE REVIEW

**Comment by Subhajit135** [comment]
@prateekiiest can you look at these PR. codeclimate is showing error in some meaningful stuff i guess. So kindly review it .

**Comment by prateekiiest** [comment]
Please provide a description in the PR what you are intending to do.

There is a PR template as you can see.

I cant make out

**Comment by prateekiiest** [comment]
You see in your first comment, there is written short description in bold.

Please explain there what your PR tries to do

**Comment by Subhajit135** [comment]
Thanks for helping me out. I am added the description of the PR

**Comment by prateekiiest** [comment]
there are some issues failing in code climate @Subhajit135 .
Its easy to fix. Can be done in a jiffy

**Comment by prateekiiest** [comment]
I guess the issues were due to .png files

**Pull request merged**
