### PR TITLE
Added Tic-Tac-Toe GUI

### PR DESCRIPTION
**Pull request by apb7**
## ISSUE NUMBER

#73 (Using Tkinter for making a GUI implementation of Tic-Tac-Toe) 

## SHORT DESCRIPTION

* Removed `code.py` and `requirements.txt`  
* Added `tic-tac-toe.py` and `README.md`   
* `tic-tac-toe.py` contains all the necessary code.  
* `README.md` provides other details to run the game.

## TESTING

The GUI has been tested against almost all cases.

### CODE REVIEW

**Comment by apb7** [comment]
@prateekiiest: Code Climate shows 10 issues to fix, all of them with `Similar blocks of code found in 2 locations. Consider refactoring.` message. These lines of code check for the victory condition and are therefore similar but not _exactly same_ .  
Code Beat, in addition to the above, also shows warnings regarding `Assignment Branch Condition` and `Cyclomatic Complexity`.  
Can you please see to it? The only way to resolve it would be to change the complete functional structure of the program.

**Comment by prateekiiest** [comment]
good work @apb7 .
Solving the tests will make it better

**Comment by prateekiiest** [comment]
Ok, I will see to it

**Comment by apb7** [comment]
@prateekiiest: I'm working on some changes. Let's see if it improves the code quality!

**Comment by prateekiiest** [comment]
there are still some issues with codebeat and codeclimate

**Comment by prateekiiest** [comment]
I am closing this. 😄 . Open if any updates

**Pull request closed without merging**
