### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by rushabhnaik16**
Voice assistant based on python

Thank you for your contribution. Please provide the details requested below.

## ISSUE NUMBER
https://github.com/prateekiiest/Code-Sleep-Python/issues/created_by/rushabhnaik16

Please provide a link to the issue this pull request addresses.

## SHORT DESCRIPTION
 A voice enabled virtual assistant.
Please provide a short description of the changes.

## TESTING
download the modules and run
Please provide the necessary steps to test the solution.

### CODE REVIEW

**Comment by prateekiiest** [comment]
@rushabhnaik16 can you fix the PEP issues and also add a demo gif with it?

**Comment by rushabhnaik16** [comment]
> @rushabhnaik16 can you fix the PEP issues and also add a demo gif with it?

I am really sorry but I am not able to understand what is the PEP issue..could you please help me?

**Comment by rushabhnaik16** [comment]
I have added a demo image and written the instructions. I have changed the code such that the pep issue might be closed. Please do check once.

**Comment by prateekiiest** [comment]
there is some indentation error. can you have a look into it?

**Comment by rushabhnaik16** [comment]
Error fixed.

**Comment by rushabhnaik16** [comment]
@prateekiiest Is the code working fine?

**Review by prateekiiest — APPROVED** [review]

**Pull request merged**
