### PR TITLE
Create Automate_chrome_dino.py

### PR DESCRIPTION
**Pull request by MayankDev-11**
Bro this will help you to automate the chrome dino using python.
If you want to try you can go here: chrome://dino

Thank you for your contribution. Please provide the details requested below.

## ISSUE NUMBER

Please provide a link to the issue this pull request addresses.

## SHORT DESCRIPTION

Please provide a short description of the changes.

## TESTING

Please provide the necessary steps to test the solution.

### CODE REVIEW

**Comment by prateekiiest** [comment]
Please provide a description of the exact problem you are trying to solve.
and also have the python file extension

**Comment by MayankDev-11** [comment]
K bro

**Comment by MayankDev-11** [comment]
Yes bro i did it

**Comment by MayankDev-11** [comment]
Did you like the project?

**Comment by prateekiiest** [comment]
@MayankDev-1 update pls

**Pull request closed without merging**
