### PR TITLE
ISSUE NUMBER: #106.

### PR DESCRIPTION
**Pull request by FinMacDov**
Thank you for your contribution. Please provide the details requested below.

## ISSUE NUMBER

 #106.

## SHORT DESCRIPTION

Added import random and added function for placing (this was missing and preventing code to run).

## TESTING

The code now outputs the histograms. Output needs double check its correct.

### CODE REVIEW

**Comment by FinMacDov** [comment]
Not that I was aware of. I am fairly new to contributing to other people project. What am I better to do in future for making the pull requests?   
hist_1
hist_2

**Comment by prateekiiest** [comment]
you are doing just great @FinMacDov . Thanks for the effort.
Before I merge in it would be great if you can fix those pep8 issues.

**Comment by FinMacDov** [comment]
Working on the pep8 issues.

**Comment by prateekiiest** [comment]
lemme know if you are facing any issues with pep8 fix

**Comment by FinMacDov** [comment]
That's the pep8 issues resolved. Let me know if there anything else you want to change with the code.

**Comment by prateekiiest** [comment]
Some more pep8 issues got involved

**Pull request merged**
