### PR TITLE
added some extra documentation to Hangman/code.py and changed requirements.txt

### PR DESCRIPTION
**Pull request by Rijul1999**
Added some documentation and provided some useful links to the Hangman code

### CODE REVIEW

**Comment by prateekiiest** [comment]
Travis is still failing

**Comment by prateekiiest** [comment]
update requirements.txt in a separate PR

**Comment by prateekiiest** [comment]
@Rijul1999 
Resolve the conflicts please

and remove everything after Python 3.2

**Comment by prateekiiest** [comment]
Some more libraries needs to be updated.
see the other codes which libraries they are using

**Comment by prateekiiest** [comment]
Resolve the conflicts pls @Rijul1999

**Comment by Rijul1999** [comment]
Hey, so I am new to Github and I don't know how to resolve the conflict when the Resolve Conflict button does not appear. Should I just make a new pull request with all the changes, @prateekiiest ?

**Comment by prateekiiest** [comment]
yeah, it will be better then if you can open a new PR with only the hangman documentation.
Closing this then?

**Comment by Rijul1999** [comment]
Yes, I will make a new PR for just Hangman then

**Pull request closed without merging**
