### PR TITLE
Issue#90

### PR DESCRIPTION
**Pull request by molex**
Thank you for your contribution. Please provide the details requested below.

## ISSUE NUMBER 90

[Link to issue](https://github.com/prateekiiest/Code-Sleep-Python/issues/90)

## SHORT DESCRIPTION

Many fixes to allow the app to run. 

## TESTING

Please provide the necessary steps to test the solution.

### CODE REVIEW

**Comment by molex** [comment]
ok, had to make some additional changes to my IDE to catch some of these PEP violations. I have resubmitted.

**Comment by prateekiiest** [comment]
some issues with code climate

**Comment by prateekiiest** [comment]
@molex any updates on this?

**Comment by prateekiiest** [comment]
I am merging this as of now

**Pull request merged**
