### PR TITLE
Connect four

### PR DESCRIPTION
**Pull request by FinMacDov**
Thank you for your contribution. Please provide the details requested below.

## ISSUE NUMBER

41

## SHORT DESCRIPTION
Added two versions of connect 4. One using pygame (code.py) and one without (simple_connect_4.py).

## TESTING

Run the games.

### CODE REVIEW

**Comment by prateekiiest** [comment]
@FinMacDov thanks for the PR.
See the PEP8 issues

**Comment by prateekiiest** [comment]
@FinMacDov any updates on this?

**Comment by FinMacDov** [comment]
On my last commit I'm sure I fixed the pep8 issues. The current issues seems to be with the complexity of the code (which would require a rework a fair bit of the code).

If I remove the unused imports, would my code be acceptable?

**Comment by FinMacDov** [comment]
Removed the unused imports

**Comment by FinMacDov** [comment]
I believe I have made the changes for the PR to be accepted.

**Comment by prateekiiest** [comment]
Thanks @FinMacDov for the changes.
Didn't get notification about the recent changes

**Pull request merged**
