### PR TITLE
4 programs in 1 PR

### PR DESCRIPTION
**Pull request by Viswas-Programs**
## SHORT DESCRIPTION

Added 4 of my mini-projects, all of them are python

## TESTING

Just run it and watch it ;) 
(I have added debug prints in function calls, so if a function should be called but isn't being called, it will be shown there with the prints)

### CODE REVIEW

**Review by prateekiiest — COMMENTED** [review]
what is this v1?

**Comment by Viswas-Programs** [comment]
oh that is the dumb version control that I made for ParodyBank program
don't worry, nothing sus is there in it.
v1 through v6 is all the same filenames, just the file's content changed throughout.

**Comment by Viswas-Programs** [comment]
and don't worry that 1 check failed (codeclimate) because I have programs here that are literal mammoths in size of code.
like it complains my 1000 line program, which is perfectly functional, and it shows an error, showing it exceeds 250 lines hehe.

**Comment by prateekiiest** [comment]
can you change your target branch to https://github.com/prateekiiest/Code-Sleep-Python/tree/hacktoberfest instead of master

**Comment by Viswas-Programs** [comment]
yeah rn

**Pull request closed without merging**
