### PR TITLE
Added Conways game of life

### PR DESCRIPTION
**Pull request by Subhajit135**
Added conways game of life using matplotlib and numpy.

### CODE REVIEW

**Comment by prateekiiest** [comment]
codeclimate fails. Try to fix that first

**Comment by prateekiiest** [comment]
check on the details @Subhajit135

**Comment by prateekiiest** [comment]
I think numpy is not imported in your code

**Comment by Subhajit135** [comment]
I imported numpy but i dont know why its showing error while importing the module.
test

**Comment by SKKSaikia** [comment]
numpy is imported as, 'import numpy as np' .

**Comment by prateekiiest** [comment]
dont submit any other code in a single PR

**Comment by prateekiiest** [comment]
Travis passes now.
Try working out with the other testcases

**Comment by prateekiiest** [comment]
I will try looking into Travis. Even if it fails, your PR can be merged. Make sure the other tests passes

**Pull request closed without merging**
